services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: fastapi dev main.py --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
      - "8081:8081"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/fast-api/app

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A worker.celery worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./app:/fast-api/app
  redis:
    image: "bitnami/redis:latest"
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
  db:
    image: postgres:17
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data # เก็บข้อมูล DB
volumes:
  pgdata:
