apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      serviceAccountName: fastapi-sa
      containers:
        - name: fastapi
          image: 361769569278.dkr.ecr.ap-southeast-1.amazonaws.com/fastapi-eks:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "dev"
            - name: S3_BUCKET_NAME
              value: "cms-fastapi-bucket"
          volumeMounts:
            - name: s3-storage
              mountPath: /mnt/s3
      volumes:
        - name: s3-storage
          persistentVolumeClaim:
            claimName: s3-pvc
