apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: 361769569278.dkr.ecr.ap-southeast-1.amazonaws.com/fastapi-eks:latest
          ports:
            - containerPort: 8000
