apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: fastapi-eks:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: fastapi-secrets # Matches the secretGenerator name
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PORT
              value: "5432"
            - name: POSTGRES_DB
              value: "dev"
