apiVersion: v1
kind: PersistentVolume
metadata:
  name: s3-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: s3-storage
  csi:
    driver: s3.csi.aws.com
    volumeHandle: cms-fastapi-bucket
    volumeAttributes:
      bucketName: cms-fastapi-bucket
