apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s3-pvc
  namespace: fastapi-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: s3-storage
  volumeName: s3-pv
