apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fastapi-dev
resources:
  - ../../base
  - namespace.yaml
  - service-account.yaml
secretGenerator:
  - name: fastapi-secrets
    envs:
      - secrets.env
    behavior: create
images:
  - name: fastapi-eks
    newName: 361769569278.dkr.ecr.ap-southeast-1.amazonaws.com/fastapi-eks
    newTag: latest
